# Generated by Django 5.0 on 2024-02-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
