# Generated by Django 5.0 on 2024-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0003_alter_dictation_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='user_current_line',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
