# Generated by Django 5.0 on 2024-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0004_alter_practice_user_current_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='user_current_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
