# Generated by Django 5.0.2 on 2024-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0006_alter_practice_user_current_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='user_current_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
