# Generated by Django 5.0.3 on 2024-04-07 00:43

import apps.dictation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0007_dictation_change_date_alter_dictation_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='lines',
            field=models.JSONField(blank=True, default=apps.dictation.models.lines_default, null=True),
        ),
    ]
