# Generated by Django 5.0.4 on 2024-06-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0008_alter_practice_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
