# Generated by Django 5.0.4 on 2024-06-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0009_alter_dictation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
