"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0.4/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0.4/ref/settings/
"""

import os

# from pathlib import Path
from dotenv import load_dotenv, find_dotenv  # type: ignore

from .base import *  # noqa

load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
RECAPTCHA_PUBLIC_KEY = os.getenv("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = os.getenv("RECAPTCHA_PRIVATE_KEY")
SILENCED_SYSTEM_CHECKS = ["django_recaptcha.recaptcha_test_key_error"]
RECAPTCHA_REQUIRED_SCORE = 0.7
CSRF_FAILURE_VIEW = "apps.dictation.views.csrf_failure"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEBUG_PROPAGATE_EXCEPTIONS = True
CSRF_FAILURE_VIEW = "apps.dictation.views.csrf_failure"


SITE_ID = 1


# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# CSP_DEFAULT_SRC = ("'none'",)
# CSP_BASE_URI = ("'self'",)
# CSP_STYLE_SRC = (
#     "'self'",
#     "cdn.jsdelivr.net/npm/",
#     "cdnjs.cloudflare.com/",
#     "fonts.googleapis.com/",
#     "https://www.googletagmanager.com/",
#     "https://www.googletagmanager.com/gtm.js",
#     "https://www.googletagmanager.com/gtag/js",
# )

# CSP_FONT_SRC = (
#     "'self'",
#     "https://fonts.gstatic.com/",
#     "https://fonts.googleapis.com/",
#     "https://cdnjs.cloudflare.com/",
# )

# CSP_SCRIPT_SRC = (
#     "'self'",
#     "'strict-dynamic'",
#     "https://www.youtube.com/",
#     "cdn.jsdelivr.net/npm/",
#     "cdnjs.cloudflare.com/",
#     "region1.google-analytics.com/",
#     "https://www.googletagmanager.com/",
#     "https://www.googletagmanager.com/gtm.js",
#     "https://www.googletagmanager.com/gtag/js",
#     "https://www.google.com/recaptcha/",
#     "https://www.gstatic.com/recaptcha/",
#     "https://analytics.google.com/",
#     "https://stats.g.doubleclick.net/",
#     "https://www.google-analytics.com/",
# )
# CSP_INCLUDE_NONCE_IN = ["script-src"]
# CSP_IMG_SRC = (
#     "'self'",
#     "img.youtube.com",
#     "i.ytimg.com/",
#     "*.google-analytics.com/",
#     "https://www.googletagmanager.com",
#     "https://www.gstatic.com/",
#     "data:",
#     "blob:",
# )
# CSP_CONNECT_SRC = (
#     "'self'",
#     "https://www.googletagmanager.com",
#     "https://www.google-analytics.com",
#     "https://analytics.google.com/",
#     "https://stats.g.doubleclick.net/",
#     "https://www.gstatic.com/",
# )
# CSP_MEDIA_SRC = ("'self'", "https://www.youtube.com/")
# CSP_FRAME_SRC = (
#     "'self'",
#     "https://www.youtube-nocookie.com/",
#     "https://www.youtube.com/embed/",
#     "https://www.youtube.com/iframe_api",
#     "https://www.googletagmanager.com/",
#     "https://googleads.g.doubleclick.net/",
#     "https://www.google.com/recaptcha/",
#     "https://recaptcha.google.com/recaptcha/",
# )
# CSP_OBJECT_SRC = ("'none'",)
# CSP_FRAME_ANCESTORS = "'self'"
# CSP_REQUIRE_TRUSTED_TYPES_FOR = ("'script'",)
