"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0.4/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0.4/ref/settings/
"""

import os

from dotenv import load_dotenv, find_dotenv  # type: ignore
from .base import *  # noqa

load_dotenv(find_dotenv())

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
RECAPTCHA_PUBLIC_KEY = os.getenv("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = os.getenv("RECAPTCHA_PRIVATE_KEY")
SILENCED_SYSTEM_CHECKS = ["django_recaptcha.recaptcha_test_key_error"]
RECAPTCHA_REQUIRED_SCORE = 0.7
CSRF_FAILURE_VIEW = "apps.dictation.views.csrf_failure"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEBUG_PROPAGATE_EXCEPTIONS = True
CSRF_FAILURE_VIEW = "apps.dictation.views.csrf_failure"


SITE_ID = 1


# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
