"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0.4/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0.4/ref/settings/
"""

import os
import sentry_sdk

from pathlib import Path

from . import base
from .base import *  # noqa

from dotenv import load_dotenv, find_dotenv  # type: ignore

# import psycopg2.extensions

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    # integrations=[DjangoIntegration()],
    # enable_tracing=True,
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    traces_sample_rate=1.0,
    # Set profiles_sample_rate to 1.0 to profile 100%
    # of sampled transactions.
    # We recommend adjusting this value in production.
    profiles_sample_rate=1.0,
)


load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
RECAPTCHA_PUBLIC_KEY = os.getenv("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = os.getenv("RECAPTCHA_PRIVATE_KEY")
SILENCED_SYSTEM_CHECKS = ["django_recaptcha.recaptcha_test_key_error"]
RECAPTCHA_REQUIRED_SCORE = 0.7
CSRF_FAILURE_VIEW = "apps.dictation.views.csrf_failure"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS").split()
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split()
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DJANGO_DEFAULT_FROM_EMAIL")
DOMAIN_NAME = os.getenv("DOMAIN_NAME")
DOMAIN = os.getenv("DOMAIN")
EMAIL_URL = os.getenv("EMAIL_URL")
EMAIL_URL_SUFFIX = os.getenv("EMAIL_URL_SUFFIX")
EMAIL_AUTH = os.getenv("EMAIL_AUTH")


SITE_ID = 3

MIDDLEWARE = base.MIDDLEWARE + ["csp.middleware.CSPMiddleware"]

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Core Settings
# https://docs.djangoproject.com/en/5.0/ref/settings/
X_FRAME_OPTIONS = "SAMEORIGIN"

SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 31536000
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_DOMAIN = os.getenv("DJANGO_SESSION_COOKIE_DOMAIN")
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24h

CSRF_TRUSTED_ORIGINS = [os.getenv("TRUSTED_DOMAIN")]

SESSION_COOKIE_NAME = "__Secure-sessionid"
CSRF_COOKIE_NAME = "__Secure-csrftoken"

# Content Security Policy
# https://django-csp.readthedocs.io/en/latest/

CSP_NONCE_USE_NONCE = True
CSP_INCLUDE_NONCE_IN = ["script-src"]

CSP_DEFAULT_SRC = ("'none'",)
CSP_BASE_URI = ("'self'",)
CSP_STYLE_SRC = (
    "'self'",
    "cdn.jsdelivr.net/npm/",
    "cdnjs.cloudflare.com/",
    "fonts.googleapis.com/",
    "https://www.googletagmanager.com/",
    "https://www.googletagmanager.com/gtm.js",
    "https://www.googletagmanager.com/gtag/js",
)

CSP_FONT_SRC = (
    "'self'",
    "https://fonts.gstatic.com/",
    "https://fonts.googleapis.com/",
    "https://cdnjs.cloudflare.com/",
)

CSP_SCRIPT_SRC = (
    "'self'",
    "'strict-dynamic'",
    "https://www.youtube.com/",
    "cdn.jsdelivr.net/npm/",
    "cdnjs.cloudflare.com/",
    "region1.google-analytics.com/",
    "https://www.googletagmanager.com/",
    "https://www.googletagmanager.com/gtm.js",
    "https://www.googletagmanager.com/gtag/js",
    "https://www.google.com/recaptcha/",
    "https://www.gstatic.com/recaptcha/",
    "https://analytics.google.com/",
    "https://stats.g.doubleclick.net/",
    "https://www.google-analytics.com/",
)
CSP_INCLUDE_NONCE_IN = ["script-src"]
CSP_IMG_SRC = (
    "'self'",
    "img.youtube.com",
    "i.ytimg.com/",
    "*.google-analytics.com/",
    "https://www.googletagmanager.com",
    "https://www.gstatic.com/",
    "data:",
    "blob:",
)
CSP_CONNECT_SRC = (
    "'self'",
    "https://www.googletagmanager.com",
    "https://www.google-analytics.com",
    "https://analytics.google.com/",
    "https://stats.g.doubleclick.net/",
    "https://www.gstatic.com/",
)
CSP_MEDIA_SRC = ("'self'", "https://www.youtube.com/")
CSP_FRAME_SRC = (
    "'self'",
    "https://www.youtube-nocookie.com/",
    "https://www.youtube.com/embed/",
    "https://www.youtube.com/iframe_api",
    "https://www.googletagmanager.com/",
    "https://googleads.g.doubleclick.net/",
    "https://www.google.com/recaptcha/",
    "https://recaptcha.google.com/recaptcha/",
)
CSP_OBJECT_SRC = ("'none'",)
CSP_FRAME_ANCESTORS = "'self'"
# CSP_REQUIRE_TRUSTED_TYPES_FOR = ("'script'",)


LOGIN_URL = "/auth/accounts/login"

# Custom user
AUTH_USER_MODEL = "dictation_auth.User"

# Redirect to profile URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = "registration/profile.html"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_DIR = Path("static")
TXT_DIR = STATIC_DIR / "txt"
IMG_DIR = STATIC_DIR / "img"

PONCTUATION = [
    ".",
    ",",
    ":",
    "!",
    "?",
    ";",
    " - ",
    '"',
    "<",
    ">",
    "/",
    "#",
    "@",
    "$",
    "£",
    "*",
    "¤",
    "|",
    "`",
]

RAVEN_CONFIG = {
    "dsn": os.getenv("SENTRY_DSN"),
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    # 'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "root": {
        "level": "DEBUG",
        "handlers": ["sentry", "console", "file"],
    },
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
    },
    "handlers": {
        "sentry": {
            "level": "INFO",
            "class": "raven.contrib.django.raven_compat.handlers.SentryHandler",
            "tags": {"custom-tag": "x"},
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "debug.log",
            "formatter": "verbose",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "level": "DEBUG",
            "handlers": ["file"],
        },
        "django": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.db.backends": {
            "level": "ERROR",
            "handlers": ["console"],
            "propagate": False,
        },
        "raven": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
        "sentry.errors": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
        "django.core.mail": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
